# Generated by Django 6.1.2 on 2026-10-09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projectapikey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDashboardPanel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("metric_name", models.CharField(max_length=512)),
                (
                    "time_range",
                    models.CharField(
                        choices=[
                            ("1h", "1 hour"),
                            ("6h", "6 hours"),
                            ("24h", "24 hours"),
                            ("7d", "7 days"),
                        ],
                        default="1h",
                        max_length=3,
                    ),
                ),
                ("service_name", models.CharField(blank=True, default="", max_length=512)),
                ("environment", models.CharField(blank=True, default="", max_length=512)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_dashboard_panels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_panels",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "position", "created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "project",
                            "metric_name",
                            "time_range",
                            "service_name",
                            "environment",
                        ),
                        name="uniq_project_dashboard_panel_query",
                    )
                ],
            },
        ),
    ]
